all: a.out

a.out: src/main.c src/game.c src/storeRoom.c src/loadRooms.c src/enemy.c src/hallway.c 
	gcc -std=c99 -Wall src/main.c src/game.c src/storeRoom.c src/loadRooms.c src/enemy.c src/hallway.c -Iinclude -lncurses